### ISSUE TITLE
Incomplete/lack documentation

### ISSUE THREAD

**Issue by yellow1912** [pritunl/pritunl#116]
I'm looking for a solution to support my need for connecting my multiple servers via a VPN with automatic distributed service. This seems like the solution.

However, I find the documents lacking for people with not so much networking background like me. 

This tutorial https://medium.com/pritunl-tutorials/pritunl-tutorial-ed50a5d2a4eb showed how to setup the main pritunl instance, however it doesn't show exactly how other hosts should join this new VPN. The "client" part seems to focus on the desktop users instead?

**Comment by zachhuff386** [comment]
Adding additional hosts is the same as adding the first one, once the additional Pritunl instance is started going to the web interface for the new host will show a prompt for the MongoDB URI. Instead of using the localhost MongoDB server the same server used for the first host will be used. Once set the new host will show up in the Hosts page and will be ready to add use. An enterprise subscription is required to do this more info is available here https://medium.com/pritunl-tutorials/pritunl-advanced-tutorial-2be5cc57dff8
