### ISSUE TITLE
Slow TCP Connection

### ISSUE THREAD

**Issue by Fattur** [pritunl/pritunl#273]
On tcp connection is really slow. on udp it's fine but if i change it to tcp it suddenly drops to 3-4 mbit area and never gets any faster.

**Comment by zachhuff386** [comment]
Don't use tcp

**Comment by Fattur** [comment]
Are you kidding me? What kind of solution of this? I am using tcp because I have to. And I have to use tcp because udp is completely blocked in some areas. So that's not even a solution. Not even close to a solution.

**Comment by eterry1388** [comment]
@zachhuff386 You should go a lot further in life if you took the time to explain things to people and not just close issues like you do.  People open issues because they are looking for help.  They should be satisfied with the resolution before closing things.  I would encourage you to read:  "How to Win Friends & Influence People".  It could help in making people like you.

Yes I know you have issues with ignorant people and lack of information.  But not everyone is as awesome as you are.  Social skills will help you get much further in life.

**Comment by Fattur** [comment]
@eterry1388  Thank you sir.
