### ISSUE TITLE
User sharing ovpn configuration

### ISSUE THREAD

**Issue by psycholyzern** [pritunl/pritunl#343]
Is it okay if all users are using the same ovpn config? If not, what are the bad things can happen?

**Comment by CaughtEx** [comment]
It depends if by config, you mean keys too. Assuming you're using pritunl, rather than pure OpenVPN, a single profile has the same key no matter what. This is likely undesireable, as it means that:

1. You cannot distinguish between people connecting to your VPN (and cannot disconnect a specific device)
2. If you need to revoke a key due to it being compromised, every client would have to download the new profile
3. Anyone can change the pin with access to the temporary profile
4. There's more chance that others can find out the key in use, as they have more devices that they can attempt to attack

It's likely that you do not want this, and therefore it is advisable that you create seperate users within pritunl. There's probably other things, but @zachhuff386 could probably tell you more than I.

**Comment by psycholyzern** [comment]
Oh thanks a lot. I have about 30 users and it is such annoying to pick each config and give it to them one by one. I was thinking if  I can use 1 config for all users.
Thanks.
