### ISSUE TITLE
Support for OpenVPN challenge/response

### ISSUE THREAD

**Issue by simonvc** [pritunl/pritunl#348]
Is there a way to setup Challenge/Response instead of concating the pin/pass and 2FA into the "Password" field?

**Comment by zachhuff386** [comment]
There isn't a significant use case for this feature.

**Comment by simonvc** [comment]
Hi Zach, Our problem is that people click save-password, then get locked out as their VPN clients keep trying to reconnect with the wrong google-auth token.
We'd be interested in sponsoring this work..

**Comment by zachhuff386** [comment]
The Pritunl client will handle all the authentication methods. It isn't clear what the support for challenge/response is across all the client platforms so enabling it could cause issues.

**Comment by obeattie** [comment]
I just wanted to jump in here to offer a little context. We're building a UK mobile-only bank, and we're evaluating possible products to use for our user-facing VPNs. We really like several features of Printunl, for instance its Google integration and the licensing model which works much better in cloud environments like ours.

One feature which is really important to us is the ability to use OTPs from something like Google Authenticator. We've previously done this with OpenVPN, but when the OTP is concatenated onto the password, users can inadvertently save their username + password + _OTP_ into their local keychain. When they try to reconnect, their client automatically sends the saved login details, and because it can't tell that part of their password is the OTP, it retries this too. If we use something like fail2ban on the server, this can easily cause the user to get locked out – or worse, get the entire office locked-out if the IP is banned.

To deal with this, I believe OpenVPN created the "[Challenge/Response Protocol](https://openvpn.net/index.php/open-source/documentation/miscellaneous/79-management-interface.html)", which causes the client to ask for the OTP in a _separate_ dialog where the info is never saved into the user's keychain. On desktop, we use [Viscosity](https://www.sparklabs.com/viscosity/), which supports this, but we'd also like to be able to use clients on mobile (iOS + Android). I've looked at the site for the [Printunl Client](https://client.pritunl.com/), but it doesn't appear to support any of the platforms which are important to us: OS X, iOS, or Android.

As @simonvc mentions, we'd be willing to sponsor the development of the challenge/response feature if you'd consider implementing it.
