### ISSUE TITLE
Paid support

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#389]
Hello. I urgently need support.
I updated version pritunl and I can not go into the web interface.

If I pay $ 250 you can help me on Skype?

It's urgent, I suffer loss !!!

**Comment by k0nsl** [comment]
Here is what I had to do in order to solve the same issue:

Check if you are running stable or development version. Check the file pritunl.list in `/etc/apt/sources.list.d` and see if it says "dev" or "stable".

I usually run development version. However, as I ran into the issue you're having I changed back to stable release.
Remove Pritunl via your package manager; I run Debian. Hence, I run `apt-get remove pritunl`. If you changed `pritunl.list` run `apt-get update`, then reinstall Pritunl again by fetching it via apt-get.

That's what solved it for me. I wrote this very hastily so these instructions are very basic but I hope it makes sense. I haven't had much sleep so if it doesn't make any sense, that's why.

If it still doesn't solve your issue, I can help you out. But I won't charge you $250. I can do it for $100.
Can you e-mail me so we can discuss and hopefully resolve the issue? My e-mail is: i.am@k0nsl.org

At any rate, this should be easy to fix.

Best wishes,
-k0nsl

**Comment by US9IDX** [comment]
I wrote to you in the mail. I sent your skype
