### ISSUE TITLE
Syntax error.

### ISSUE THREAD

**Issue by dragon2611** [pritunl/pritunl#59]
Tried updating to the latest version and was getting a syntax error, I think it might be down to commit 06d1d20dabc680fdfe81525c172abe589d16f12e as it's in pritunl/handlers/server.py

I think the ) at the end of 'tls_auth_key', 'ca_certificate']) but now need to be removed since there is no longer a corresponding ( looks to have been removed as part of the change.

That said I was only looking at the specific commit and I'm not a programmer/coder so I might be totally mistaken.

**Comment by zachhuff386** [comment]
Fixed in commit above, if you're running a server it's best to use the packages or the releases in https://github.com/pritunl/pritunl/releases. There are sometimes changes made to the database that won't have migration code added until release which could corrupt your database and require manually fixing it.

**Comment by dragon2611** [comment]
Ahh Ok, 

It's running on a Cubbieboard3 sitting at home, so it wouldn't be world ending if I was to accidentally kill it as it's only used sometimes If I want remote access to my home network or to secure communications over a public hotspot.
