### ISSUE TITLE
Is it possible to add  openvpn "port-share" option?

### ISSUE THREAD

**Issue by wwarne** [pritunl/pritunl#63]
There are some places where only 80 and 443 ports are allowed out. So one of my openvpn servers runs on 443 port, shared with nginx. It's a standard openvpn feature.
Is it possible to add `port-share` options to pritunl gui?
In server config it looks like:
`proto tcp`
`port 443`
`port-share 127.0.0.1 9999` -> in this case nginx is listening to this port.
Thank you.

**Comment by jeremy5189** [comment]
I'm running Pritunl on Ubuntu 14.04. I manually edit ``/usr/lib/python2.7/dist-packages/pritunl/server/instance.py`` and add the following code after ``server_conf = OVPN_INLINE_SERVER_CONF`` (around line 149)

```
if self.server.port == 443:
    server_conf += 'port-share localhost 4430\n'
```

But this isn't a long-term solution since the file will be overwritten after running ``apt-get update``. So git branch is recommended.

**Comment by zachhuff386** [comment]
There isn't any significant use cases for this feature and it will likely never be added.

**Comment by hastou** [comment]
You can use sslh to run ssh, openvpn and apache server on 443 port.
