### ISSUE TITLE
Ability To Offer Different Configs By Port

### ISSUE THREAD

**Issue by rholloway** [pritunl/pritunl#73]
What is the recommendation for addressing the following situation? 

On our previous openvpn setup, we exposed openvpn server over two ports. When connected to the first port, it pushed routes to route all traffic through the tunnel, but if the user connected to the second port, it just pushed local routes.

Is there a fairly easy way to do this with pritunl? I thought maybe adding a second server with second port, but it looks like the user certs are tied to an organization and the organization tied to the server. We would need to create everyone an account under each organization for the different 'configurations' and then they would choose the cert of choice / org. upon connection. This could work with some scripting to replicate users between orgs probably, but maybe there is a better way?

**Comment by zachhuff386** [comment]
Organizations can be attached to multiple servers but two config files will always be needed for the tls-auth key. You could disable tls-auth and create two servers with the same organizations and the config file will work with both servers by changing the port. But this can only be done by going on to the mongodb database and disabling tls-auth on the server. There may also be an issues with the users static IP which is related to the id in the config file. This could cause the client to get a random IP instead of the IP listed for the user.
