### ISSUE TITLE
Timeout after reinstall with mongodb backup

### ISSUE THREAD

**Issue by Pauzie** [pritunl/pritunl#83]
... after new installation and restore data from mongodump, the pritunl application started. If i try to start the server, i have a timeout error.

What can i do?

**Comment by zachhuff386** [comment]
This is issue caused by the host uuid stored in `/var/lib/pritunl/pritunl.uuid` changing which is used in the enterprise edition to allow multiple hosts. The uuid is used to identify each pritunl server in the cluster. When you are starting the new server you create a new host and then attempt to start vpn servers on a host that doesn't exists. You'll need to stop the server find the original host id in the `hosts` collection which will be the one that is listed as host in the `servers` collection. Then take that id and save it in `/var/lib/pritunl/pritunl.uuid` and delete any other hosts in the `hosts` collection. In a future release this issue will get fixed to make restoring backups easier.
