### ISSUE TITLE
MongoDB high cpu usage

### ISSUE THREAD

**Issue by yarreg** [pritunl/pritunl#84]
Hello,
I have a simple instance running Pritunl 1.0.544.74, mongodb 2.6.8
Everything works well, but CPU usage of mongodb process exceeds 20%.
Mongodb uses only Pritunl server. I have 3 client connected to VPN.
May be perhaps to create mongodb indexes?

Mongotop - http://pastebin.com/tZebgYys

Thanks.

**Comment by zachhuff386** [comment]
The `messages` collection is used with a tailable cursor for pubsub event's. It is used to allow the web interface to automatically update when changes occur as well as system messages between nodes in a distributed pritunl cluster. The `logs` collection is used for the vpn server output if you are running a server with debug output this collection will have more use. I believe indexes show up separately in `mongotop` and it's unlikely the cpu usage because of the indexes. It's possible you server is currently pooling user certs/dh params. User certs take about 3-5 seconds to create a 1536bit dh param can take 1-15 minutes. To allow the web interface and api to instantly create new users and servers these resources are created in advanced and stored in the database. When you first start the server it will use most of cpu to fill the cert/dhparam pools this process finishes in about 5 minutes on a small server. Most likely you are running pritunl on a slow server with little memory a typical output should have messages `<5ms` and logs `<1ms`.
